services:
  - type: web
    name: hostyourcode
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python hostyourcode.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "10000"
